@startuml todo

class Item{}
class ItemList{}
class ItemListStatusController{
    + addItem(item: Item, itemList: ItemList): ItemList
    + deleteItem(item: Item, itemList: ItemList): ItemList
    + changeItemCompleteStatus(item: Item, itemList: ItemList): ItemList
}
class Add{
    + execute(item: Item, itemList: ItemList): ItemList
}
class Delete{
    + execute(item: Item, itemList: ItemList): ItemList
}
class ChangeComplete{
    + execute(item: Item, itemList: ItemList): ItemList
}



class DataManager{
    + save(itemList: ItemList): void
    + load(itemList: ItemList): void
}
class RenderCardList{
    + all(itemList: ItemList): void
    + complete(itemList: ItemList): void
    + uncomplete(itemList: ItemList): void
}
class Form{}
class Trash{}
class Complete{}
class Category{}
class Card{}

class DataConverter{
    + convertFormDataToItem(form: Form): Item
    + convertTrashDataToItem(trash: Trash): Item
    + convertCompleteDataToItem(complete: Complete): Item
    + convertCardDataToItem(card: Card): Item
}

class ConvertFormDataToItem{
    + execute(form: Form): Item
}

class ConvertTrashDataToItem{
    + execute(form: Form): Item
}

class ConvertCompleteDataToItem{
    + execute(form: Form): Item
}

class ConvertCardDataToItem{
    + execute(card: Card): Item
}

class RegisterFormEvent{
    + submit(form: Form): void
}

class RegisterTrashEvent{
    + onClick(trash: Trash): void
}
class RegisterCompleteEvent{
    + onClick(complete: Complete): void
}
class RegisterCategoryEvent{
    + onClick(category: Category): void
}
class RegisterCardEvent{
    + onClick(card: Card): void
}
class AllRender{
    + execute(itemList: ItemList): void
}
class CompleteRender{
    + execute(itemList: ItemList): void
}
class UncompleteRender{
    + execute(itemList: ItemList): void
}
class RenderDetailCard{
    + execute(item: Item): void
}

Item <-- Add
Item <-- Delete
Item <-- ChangeComplete

Add <-- ItemListStatusController
Delete <-- ItemListStatusController
ChangeComplete <-- ItemListStatusController

ItemList <-- DataManager
ItemList <-- RenderCardList
ItemList <-- ItemListStatusController

Form <-- DataConverter
Trash <-- DataConverter
Complete <-- DataConverter

RegisterFormEvent <-- Form
RegisterTrashEvent <-- Trash
RegisterCompleteEvent <-- Complete
RegisterCategoryEvent <-- Category

ConvertFormDataToItem <-- DataConverter
ConvertTrashDataToItem <-- DataConverter
ConvertCompleteDataToItem <-- DataConverter

Delete <-- ConvertFormDataToItem
Add <-- ConvertTrashDataToItem
ChangeComplete <-- ConvertCompleteDataToItem

AllRender <-- RenderCardList
CompleteRender <-- RenderCardList
UncompleteRender <-- RenderCardList

Category <-- RenderCardList
RegisterCardEvent <-- Card
Card <-- DataConverter
ConvertCardDataToItem <-- DataConverter
RenderDetailCard <-- ConvertCardDataToItem
Item <-- RenderDetailCard
@enduml
