@startuml todo
    class Todo{
        + title: string
        + isCompleted: boolean
        + id: number
    }
    class TodoList{
        + dataArray: Todo[]
    }
    class Add{
        + execute(todo: Todo, todoList: TodoList): TodoList
    }
    class Delete{
        + execute(id: number,todoList: TodoList): TodoList
    }
    class ChangeCompleted{
        + execute(todo: Todo, todoList:TodoList): TodoList
    }
    class Show{
        + All(toDoList: TodoList): void
        + unCompletedAll(toDoList: TodoList): void
        + completedAll(toDoList: TodoList): void
    }
    class DataManager{
        + save(todoList: TodoList): void
        + load(todoList: TodoList): void
    }

    Todo <|-- Delete
    Todo <|-- Add
    Todo <|-- ChangeCompleted

    TodoList <|-- Show
    TodoList <|-- DataManager

    Delete <|-- TodoList
    Add <|-- TodoList
    ChangeCompleted <|-- TodoList
@enduml
